sudo: required
services:
  - docker


before_install:
  - docker build -t sonupatel10906997/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sonupatel10906997/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-964808039275"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

